config/routes.rb
Rails.application.routes.draw do
  get 'votes/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  get '/posts', to: redirect('/'), as: 'posts'
  resources :posts, except: [:index] do
    resources :votes, only: [:create]
  end

  resources :users, only: [:show] do
    resources :posts, only: [:index]
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :votes
  has_many :users, through: :votes
  belongs_to :user, foreign_key: "author_id"

  validates :title, presence: true
  validates :body, presence: true
  scope :ordered_by_votes, -> {joins(:votes).group('posts.id').order('SUM("votes.value")')}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :votes
  has_many :voted_posts, through: :votes, source: :post
  has_many :authored_posts, class_name: "Post", foreign_key: "author_id"

  validates :username, presence: true, uniqueness: {case_sensitive: :false}
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :value, presence: true, inclusion: { in: [-1, 1],
  message: "Your vote must be either 1 or -1."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user
  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:new, :show, :edit, :update, :destroy]
  before_action :redirect_if_not_authorized!, only: [:edit, :update, :destroy]
  before_action :redirect_if_post_nonexistent!, only: [:show]

  def index
    if params[:user_id]
      if set_user
        @nested = true
        @user = User.find_by(id: params[:user_id])
        @posts = @user.authored_posts
      else
        flash[:message] = "User does not exist!"
        redirect_to root_path
      end
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.authored_posts.build(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @vote = Vote.new
    @vote_total = @post.votes.sum(&:value)
    @user_vote = Vote.find_by(user: current_user, post: @post)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:message] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:message] = "Post successfully destroyed!"
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
  end

  def redirect_if_post_nonexistent!
    if @post.nil?
      flash[:message] = "Post does not exist!"
      redirect_to posts_path
    end
  end

  def redirect_if_user_nonexistent!
    if @user.nil?
      flash[:message] = "User does not exist!"
      redirect_to posts_path
    end
  end

  def redirect_if_not_authorized!
    if @post.user != current_user
      redirect_to '/posts'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:message] = "Something went wrong."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = "Successfully Signed Up!"
      redirect_to posts_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @post = Post.find_by(params[:post_id])
    if !@post
      flash[:message] = "No such post!"
      redirect_to posts_path
    end

    @vote = current_user.votes.find_or_initialize_by(post: @post)

    if @vote.value && @vote.value == params[:vote][:value].to_i
      @vote.destroy
      flash[:message] = "Unvote successful!"
    elsif @vote.update(vote_params)
      flash[:message] = "Vote successful!"
    else
      flash[:message] = "Something went wrong."
    end
    redirect_to post_path(@post)
  end

  private
  def vote_params
    params.require(:vote).permit(:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fleddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
    <h1 style="text-align: center"><%= link_to "FLEDDIT", root_path %></h1>
    <% if logged_in? %>
      <div style="text-align: center">
        <%= link_to "New Post", new_post_path %> |
        <%= link_to "Profile", user_posts_path(current_user) %> |
        <%= link_to "Log Out", logout_path, method: :delete %>
      </div>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
    <% end %>
    <br><br>
    <div style="text-align: center">
      <%= flash[:message] if flash[:message] %>
    </div>
      <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit a Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<% if @nested %>
  <h2 class='header2' style="text-align: center"><%= @user.username.capitalize %>'s Posts</h2>
<% else %>
  <h2 style="text-align: center">All Posts</h2>
<% end %>
<% @posts.each do |post| %>
  <div class= 'container border shadow-sm p-2 mb-2 bg-white rounded'>
    <h4><%= post.votes.sum(&:value) %> <%= link_to post.title, post_path(post) %></h4>
    <p><%= post.user.username %></p>
    <% if @nested && post.user == current_user %>
      <%= link_to "Edit Post", edit_post_path(post) %>
      <%= link_to "Delete Post", post_path(post), method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Create a New Post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %><br>
<h3><%= @vote_total  %> <%= link_to @post.user.username, posts_path(@post.user) %></h3>
<p><%= @post.body %></p>

<%= form_for [@post, @vote] do |f|%>
  <%= f.hidden_field :value, value: 1 %>
  <% if @user_vote && @user_vote.value == 1 %>
  <%= f.submit value: "Unvote!"%>
  <% else %>
    <%= f.submit value: "Vote Up!"%>
  <% end %>
<% end %>

<%= form_for [@post, @vote] do |f|%>
  <%= f.hidden_field :value, value: -1 %>
  <% if @user_vote && @user_vote.value == -1 %>
  <%= f.submit value: "Unvote!"%>
  <% else %>
    <%= f.submit value: "Vote Down!"%>
  <% end %>
<% end %>

<% if @post.user == current_user %>
  <%= link_to "Edit Post", edit_post_path(@post) %>
  <%= link_to "Delete Post", post_path(@post), method: :delete %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<% if @user.errors %>
  <% @user.errors.full_messages.each do |error| %>
    <%= error %>
    <br><br>
  <% end %>
<% end %>
<%= form_for @user, url: '/signup' do |f| %>
  <%= f.label :username %>
  <div><%= f.text_field :username %></div>

  <%= f.label :password %>
  <div><%= f.password_field :password %></div>
  <%= f.label :password_confirmation %>
  <div><%= f.password_field :password_confirmation %></div>
  <%= f.submit %>
<% end %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>